# Generated by Django 6.0.6 on 2026-06-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_familyshopping_moneybyphone_workasleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyshopping',
            name='title',
            field=models.CharField(default='Покупки для семьи', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='moneybyphone',
            name='title',
            field=models.CharField(default='Заработок по телефону', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='workasleader',
            name='title',
            field=models.CharField(default='Работа лидером', max_length=200, verbose_name='Заголовок'),
        ),
    ]
