# Generated by Django 6.0.6 on 2026-06-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_familyshopping_title_alter_moneybyphone_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gifts', 'Подарки для новичков'), ('starter', 'Стартовая программа'), ('deals', 'Выгодные предложения')], max_length=20, verbose_name='Раздел')),
                ('image', models.ImageField(upload_to='home_offers/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка (порядок)')),
            ],
            options={
                'verbose_name': 'Предложение на Главной',
                'verbose_name_plural': 'Главная страница',
                'ordering': ['category', 'order', '-id'],
            },
        ),
    ]
