# Generated by Django 6.0.6 on 2026-06-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDealOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/deals/', verbose_name='Фото предложения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Главная: Выгодные предложения',
                'verbose_name_plural': 'Главная: Выгодные предложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeGiftsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='home/gifts/', verbose_name='Фото 1 (Беларусь)')),
                ('image_2', models.ImageField(upload_to='home/gifts/', verbose_name='Фото 2 (Россия)')),
                ('image_3', models.ImageField(upload_to='home/gifts/', verbose_name='Фото 3 (Казахстан)')),
                ('image_4', models.ImageField(upload_to='home/gifts/', verbose_name='Фото 4 (Таджикистан)')),
                ('image_5', models.ImageField(upload_to='home/gifts/', verbose_name='Фото 5 (Кыргызстан)')),
            ],
            options={
                'verbose_name': 'Главная: Подарки для новичков',
                'verbose_name_plural': 'Главная: Подарки для новичков',
            },
        ),
        migrations.CreateModel(
            name='HomeStarterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='home/starter/', verbose_name='Фото 1 (Беларусь)')),
                ('image_2', models.ImageField(upload_to='home/starter/', verbose_name='Фото 2 (Россия)')),
                ('image_3', models.ImageField(upload_to='home/starter/', verbose_name='Фото 3 (Казахстан)')),
                ('image_4', models.ImageField(upload_to='home/starter/', verbose_name='Фото 4 (Таджикистан)')),
                ('image_5', models.ImageField(upload_to='home/starter/', verbose_name='Фото 5 (Кыргызстан)')),
            ],
            options={
                'verbose_name': 'Главная: Стартовая программа',
                'verbose_name_plural': 'Главная: Стартовая программа',
            },
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
